# vi: set ft=yaml :

user:
  name: alex
  uid: 1000
  group: users
  shell: /usr/sbin/zsh
  email: acyxou@gmail.com

# NOTE: The below 2 variables should not need to be changed if you cloned
# this repo to '~/arch-bootstrap'
# Local home directory
wsl_bootstrap_user_home: "{{ '~' | expanduser }}"
# Where this repo lives. Probably don't need to change this.
wsl_bootstrap_home: "{{wsl_bootstrap_user_home}}/code/arch-bootstrap"

git:
  # Name used in commit messages
  full_name: Alex Sukhov
  # Github username
  user: cyxou
  # If you use github, this should be the same as the email used on Github
  email: acyxou@gmail.com
  # GPG Key ID used to sign git commits
  # See https://github.com/pstadler/keybase-gpg-github setup instructions
  signing_key:

hostname: xps
 
# Check it out with ifconfig
wifi_interface: wlp59s0

base_packages:
  - tree
  - ack
  - xclip
  - zip
  - unrar
  - tig
  - jq
  - python-setuptools
  - alsa-utils
  - gopass
  - pcmanfm
  - httpie
  - unclutter
  - fzf
  - ripgrep

xorg_packages:
  - xorg-server
  - xorg-xinit
  - xorg-xmodmap
  - xorg-xbacklight
  - xf86-input-libinput
  - libinput
  - lxdm

aur:
  dir: aur
  packages:
    palemoon-bin

ssh:
  port: 22
  generate_user_key: yes
# user_key:

base_fonts:
  - ttf-dejavu
  - ttf-ubuntu-font-family
  - terminus-font

aur_fonts:
  - nerd-fonts-source-code-pro
  - nerd-fonts-hack
