- name: Set up local development environment
  hosts: local
  roles:
    - role: 'linux-lts'
      when: ansible_os_family == "Archlinux" and use_lts_kernel
    - tweaking
    - power-saving
    - video-drivers
    - base
    - x11
    - lxdm
    - ssh
    - net
    - aur
    - { role: 'yaourt', tags: ['arch'] }
    - fonts
    - awesome
    - base16
    - wsl
    - git
    - pip
    - zsh
    - tmux
    - docker
    - docker-compose
    - nvm
    - aws
    - nodejs
    - npm
    - termite
    - vim
    - neovim
    - browsers
    - minikube
    - kops
    - systemd-timesyncd

# vars_prompt:
#   - name: user_password
#     prompt: "Enter desired user password"
