- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- name: Make directory for user SSH key
  file:
    path: "{{ arch_bootstrap_user_home }}/.ssh"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Install user SSH key
  copy:
    src: "{{ ssh.user_key }}"
    dest: "{{ arch_bootstrap_user_home }}/.ssh/id_rsa"
    mode: 600
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  when: ssh.user_key is defined

- name: Generate SSH id_rsa key
  block:
    - name: Check that the id_rsa key already exists
      stat:
        path: "{{ arch_bootstrap_user_home}}/.ssh/id_rsa"
      register: stat_result

    - name: Generate new id_rsa, if it doesn't exist
      command : ssh-keygen -q -t rsa -f "{{ arch_bootstrap_user_home}}/.ssh/id_rsa" -C "" -N ""
      when: stat_result.stat.exists == False
  when: ssh.generate_user_key
