# Installation and setup
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

# Configuration
- name: Check if zshrc already exists
  stat: path="{{ arch_bootstrap_user_home }}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{ arch_bootstrap_user_home }}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ arch_bootstrap_user_home }}/.oh-my-zsh"
  register: cloning

- name: Link zshrc.symlink to ~/.zshrc
  file:
    src: "{{ arch_bootstrap_home }}/roles/zsh/files/zshrc.symlink"
    dest: "{{ arch_bootstrap_user_home }}/.zshrc"
    state: link
    force: yes
  when: cloning is succeeded

- name: Set zsh as default shell
  user:
    name: "{{ lookup('env','USER') }}"
    shell: /usr/bin/zsh
  become: yes

- import_tasks: powerlevel10k.yml
