- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install termite
  pacman:
    name: termite
    state: present
  become: yes

- name: Provide termite config file
  block:
    - name: Create .config/termite directory if doesn't exist
      file:
        path: "{{ arch_bootstrap_user_home }}/.config/termite"
        state: directory

    - name: Symlink termite config file
      file:
        src: "{{ arch_bootstrap_home }}/roles/termite/files/config"
        dest: "{{ arch_bootstrap_user_home }}/.config/termite/config"
        state: link
        force: yes
        state: link
