- name: Install i3lock
  pacman:
    name: i3lock
    state: present
  become: yes

- name: Copy i3lock@.service to systemd
  template:
    src: i3lock.service.j2
    dest: "/etc/systemd/system/i3lock@user.service"
  become: yes

- name: Enable i3lock@user.service
  systemd:
    name: i3lock@user.service
    enabled: yes
  become: yes
