- name: Install VirtualBox
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualbox
    - virtualbox-host-modules-arch
    - virtualbox-guest-utils
    - virtualbox-guest-modules-arch
  become: yes
