- name: Install lxdm
  pacman:
    name: lxdm
    state: present
  become: yes

- name: Install lxdm themes
  aur:
    name: lxdm-themes

- name: Enable lxdm.service
  systemd:
    name: lxdm.service
    enabled: yes
  become: yes

- name: Copy lxdm.conf
  copy:
    src: "{{ arch_bootstrap_home }}/roles/lxdm/files/lxdm.conf"
    dest: /etc/lxdm/lxdm.conf
  become: yes
