- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Adding current user to group bumblebee
  user:
    name: "{{ ansible_user_id }}"
    groups: bumblebee
    append: yes
    state: present
  become: yes

- name: Enable bumblebeed.service
  systemd:
    name: bumblebeed.service
    enabled: yes
  become: yes

# Only use this if you don't install bumblebee
#- include: disable-discrete-gpu.yml
