- name: Install packages to allow apt to use a repository over HTTPS
  apt: name={{ item }} state=present
  with_items:
   - apt-transport-https
   - ca-certificates
   - software-properties-common
   - python-setuptools 
  become: yes

- name: Import Docker CE repository gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  become: yes

- name: Add Docker CE repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  register: apt_result
  until: apt_result is succeeded
  retries: 3
  delay: 1
  become: yes
  ignore_errors: yes