- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- name: Enable docker.service
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Adding current user to group docker
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
    state: present
  become: yes
