- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Make awesome mine
  block:
    - name: Make sure ~/.config/awesome exists
      file:
        path: "{{ arch_bootstrap_user_home }}/.config/awesome"
        state: directory

    - name: Install lain
      git:
        repo: https://github.com/lcpz/lain
        dest: "{{ arch_bootstrap_user_home }}/.config/awesome/lain"

    - name: Install freedesktop
      git:
        repo: https://github.com/lcpz/awesome-freedesktop.git
        dest: "{{ arch_bootstrap_user_home }}/.config/awesome/freedesktop"

    - name: Install awesome-copycats themes
      git:
        repo: https://github.com/lcpz/awesome-copycats.git
        dest: "{{ arch_bootstrap_user_home }}/.config/awesome/awesome-copycats"

    - name: Symlink my theme folder
      file:
        src: "{{ arch_bootstrap_home }}/roles/awesome/files/themes"
        dest: "{{ arch_bootstrap_user_home }}/.config/awesome/themes"
        state: link
        force: yes
        follow: no

- name: Backup existing rc.lua file
  block:
    - name: Check if rc.lua exists
      stat: path="{{ arch_bootstrap_user_home }}/.config/awesome/rc.lua"
      register: rclua_stat

    - name: Backup rc.lua file
      command: "mv {{ arch_bootstrap_user_home }}/.config/awesome/rc.lua {{ arch_bootstrap_user_home }}/.config/awesome/rc.lua.bak"
      args:
        creates: "{{ arch_bootstrap_user_home }}/.config/awesome/rc.lua.bak"
      when: rclua_stat.stat.exists

- name: Symlink the rc.lua file
  file:
    src: "{{ arch_bootstrap_home }}/roles/awesome/files/rc.lua"
    dest: "{{ arch_bootstrap_user_home }}/.config/awesome/rc.lua"
    state: link
    force: yes

#- name: Symlink themes.lua files
#  block:
#  - name: Symlink powerarrow-dark theme.lua
#    file:
#      src: "{{ arch_bootstrap_home }}/roles/awesome/files/powerarrow-dark-theme.lua"
#      dest: "{{ arch_bootstrap_user_home }}/.config/awesome/themes/powerarrow-dark/theme.lua"
#      state: link
#      force: yes
#  - name: Symlink powerarrow theme.lua
#    file:
#      src: "{{ arch_bootstrap_home }}/roles/awesome/files/powerarrow-theme.lua"
#      dest: "{{ arch_bootstrap_user_home }}/.config/awesome/themes/powerarrow/theme.lua"
#      state: link
#      force: yes
