- name: Install base fonts
  pacman:
    name: "{{ item }}"
    state: latest
  with_items: "{{ base_fonts }}"
  become: yes

- name: Install AUR fonts
  aur:
    name: "{{ item }}"
  with_items: "{{ aur_fonts }}"
  tags:
    - aur
